pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                bat 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                // Checkout the repository
                checkout scm
                
                // Execute the shell script from the checked-out repository
                bat 'sh ./jenkins/scripts/deliver.sh'
            }
        }
    }
}
